### ISSUE TITLE
Install.inf cannot run in ARM

### ISSUE THREAD

**Issue by JordanQD** [PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x#4]
### Issue description

![image](https://user-images.githubusercontent.com/25655766/216503970-25884172-794c-4837-a370-5f2f0e160180.png)

### How to reproduce this issue?

Just install the Install.inf

### Operating system

Windows

### Details

v2.2pro

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.2/issues' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not already fixed

**Comment by PSGitHubUser1** [comment]
More info is needed.. ARM64 ??

**Comment by PSGitHubUser1** [comment]
You should contact to the creator as I am not the creator, I can't do anything.. (maybe)

**Comment by PSGitHubUser1** [comment]
how you're using win 11 with x86

**Comment by PSGitHubUser1** [comment]
maybe its installed but its showing 
![](https://user-images.githubusercontent.com/25655766/216503970-25884172-794c-4837-a370-5f2f0e160180.png)

let you try this command `rundll32.exe shell32.dll,Control_RunDLL main.cpl @0,1` and select the cursor...

but to run this command press "Windows Key + R" and tehn paste the command..

**Comment by PSGitHubUser1** [comment]
Or .inf doesn't work with ARM. Let me help you.
