### ISSUE TITLE
Add tail version

### ISSUE THREAD

**Issue by SirEthanator** [PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x#6]
### Feature description

Can you please add the brand new version with a tail?

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature <a href='https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.2/issues' target='_blank'>is not already asked.</a>
- [X] I have checked that this feature is not already implemented

**Comment by felipenneto** [comment]
Please add the tail version.

![windows_11_hdpi_tail_cursor_concept_by_jepricreations_dfww79y-fullview](https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x/assets/106479636/a385c913-77b1-4980-b534-ee6b5134250f)

**Comment by PSGitHubUser1** [comment]
what is tail version? what does it mean?

**Comment by FadeMind** [comment]
@PSGitHubUser1 
![20230520-1684581254](https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x/assets/9846948/b6feead3-433b-4ce6-9dc9-5fb46da1b3de)
![20230520-1684581239](https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x/assets/9846948/aec9305b-74a0-4bde-804a-be4d2ef67474)

samples for comparing taken from http://www.rw-designer.com/gallery?search=tail+cursors

**Comment by SirEthanator** [comment]
Sorry, I forgot to include a link in the original post. They can be found here: https://www.deviantart.com/jepricreations/art/Windows-11-Hdpi-Tail-Cursor-Concept-962242774

**Comment by Dhyfer1** [comment]
**+1** I also want the Tail version

**Comment by SirEthanator** [comment]
Is anything going to be done?

**Comment by PSGitHubUser1** [comment]
See, I am trying as hard to get on platforms. And I don't want to go to dark web as it is just very scary. Also, its an illegal repo, so you have to wait, even I did not bought the cursors. I'm trying...

**Comment by SirEthanator** [comment]
I believe the tail version is a separate cursor pack. The original source is here: https://www.deviantart.com/jepricreations/art/Windows-11-Hdpi-Tail-Cursor-Concept-962242774
And would you also be able to update the normal one? The default loading spinner on the dark version has been changed.

**Comment by Dhyfer1** [comment]
@PSGitHubUser1 Someone from Ukraine bought the "Windows 11 Cursors Concept HD v2" pack and sent it to your gmail, as you said [here](https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x/issues/5#issuecomment-1484918171). If you still have his email, you can contact him and ask him if he has bought the cursors Tail pack, and if he has bought it, you could ask him if he can share it with you.

**Comment by PSGitHubUser1** [comment]
Hmm, let me try.

**Comment by PSGitHubUser1** [comment]
![picture.jpg](https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x/assets/90406016/cdfbd32b-694b-435c-b820-c31d5345e020)

**Comment by SirEthanator** [comment]
Okay, understood.

**Comment by PSGitHubUser1** [comment]
Nope. I will not close this issue until I will feel that "I failed".

**Comment by Dhyfer1** [comment]
It's a shame.

Well, even if Deviantart didn't have its own currencies, you couldn't use Amazon or Flipkart gift cards to buy the cursor packs, since these cursor packages can also be purchased with a credit card, with Paypal or with bitcoins.

Also, this pack of cursors can not only be purchased on Deviantart but also on [Ko-fi](https://ko-fi.com/s/d9f85e6821)

**Comment by Dhyfer1** [comment]
> And would you also be able to update the normal one? The default loading spinner on the dark version has been changed.

The update they mention only applies to the free version, dated the 21st of this month, which says: "Change the default loading color of dark version, to match Windows 11 style."

Instead, the last update of the pro version is dated March 3.
