### ISSUE TITLE
about the style

### ISSUE THREAD

**Issue by HMwancheng** [PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.x#9]
### Feature description

[so sorry of my poor english]

I like this cursor, it look's so beautiful

but me have a advise（also it's cause me a little don't like）
can make a thin black line(around the arrow) version? (light type), i think the black line around the arrow too thick for me

TKS!

### Issue tracker rule checks (please read carefully)

- [X] I have checked that this feature <a href='https://github.com/PSGitHubUser1/Windows-11-Cursor-Concept-Pro-v2.2/issues' target='_blank'>is not already asked.</a>
- [X] I have checked that this feature is not already implemented

**Comment by PSGitHubUser1** [comment]
Well, I have not made these cursors, its made by jepri.
And its paid... I am just redistributing it for free..  which is illegal soo..

Ask the real author to do this... And download these cursors and save them b'cuz its not confirm that how long this project will be public. Can be closed anytime.
